root:
  askformore: false
  autoclip: false
  autoimport: false
  autosync: true
  cliptimeout: 0
  editrecipients: false
  nocolor: false
  noconfirm: false
  nopager: false
  path: gpgcli-gitcli-fs+file:///Users/tagir/git/password-store/root
  safecontent: true
  usesymbols: false
  notifications: false
mounts:
  devops:
    askformore: false
    autoclip: false
    autoimport: false
    autosync: true
    cliptimeout: 0
    editrecipients: false
    nocolor: false
    noconfirm: false
    nopager: false
    path: gpgcli-gitcli-fs+file:///Users/tagir/git/password-store/devops
    safecontent: true
    usesymbols: false
    notifications: false
  kk:
    askformore: false
    autoclip: false
    autoimport: false
    autosync: true
    cliptimeout: 0
    editrecipients: false
    nocolor: false
    noconfirm: false
    nopager: false
    path: gpgcli-gitcli-fs+file:///Users/tagir/git/password-store/kulturklick
    safecontent: true
    usesymbols: false
    notifications: false
version: 1.7.2
