root:
  askformore: false
  autoclip: false
  autoimport: false
  autosync: true
  check_recipient_hash: false
  cliptimeout: 0
  concurrency: 1
  editrecipients: false
  nocolor: false
  noconfirm: false
  nopager: false
  notifications: false
  path: gpgcli-gitcli-fs+file:///home/tagir/git/password-store/root
  recipient_hash: {}
  safecontent: true
  usesymbols: false
mounts:
  a:
    askformore: false
    autoclip: false
    autoimport: false
    autosync: true
    check_recipient_hash: false
    cliptimeout: 0
    concurrency: 1
    editrecipients: false
    nocolor: false
    noconfirm: false
    nopager: false
    notifications: false
    path: gpgcli-gitcli-fs+file:///home/tagir/a/passwordstore
    recipient_hash:
      .gpg-id: 393137333145373443343446414633444436394643453730443336303335393535424243433633420a443732453539314341353042373441373343303041413942304245373142434246363332463543300aa69f73cca23a9ac5c8b567dc185a756e97c982164fe25859e0d1dcc1475c80a615b2123af1f5f94c11e3e9402c3ac558f500199d95b6d3e301758586281dcd26
    safecontent: true
    usesymbols: false
  core:
    askformore: false
    autoclip: false
    autoimport: false
    autosync: true
    check_recipient_hash: false
    cliptimeout: 0
    concurrency: 1
    editrecipients: false
    nocolor: false
    noconfirm: false
    nopager: false
    notifications: false
    path: gpgcli-gitcli-fs+file:///home/tagir/git/core/passwordstore
    recipient_hash: {}
    safecontent: true
    usesymbols: false
  devops:
    askformore: false
    autoclip: false
    autoimport: false
    autosync: true
    check_recipient_hash: false
    cliptimeout: 0
    concurrency: 1
    editrecipients: false
    nocolor: false
    noconfirm: false
    nopager: false
    notifications: false
    path: gpgcli-gitcli-fs+file:///home/tagir/git/password-store/devops
    recipient_hash: {}
    safecontent: true
    usesymbols: false
  kulturklick:
    askformore: false
    autoclip: false
    autoimport: false
    autosync: true
    check_recipient_hash: false
    cliptimeout: 0
    concurrency: 1
    editrecipients: false
    nocolor: false
    noconfirm: false
    nopager: false
    notifications: false
    path: gpgcli-gitcli-fs+file:///home/tagir/git/password-store/kulturklick
    recipient_hash: {}
    safecontent: true
    usesymbols: false
  portal:
    askformore: false
    autoclip: false
    autoimport: false
    autosync: true
    check_recipient_hash: false
    cliptimeout: 0
    concurrency: 1
    editrecipients: false
    nocolor: false
    noconfirm: false
    nopager: false
    notifications: false
    path: gpgcli-gitcli-fs+file:///home/tagir/git/portal/passwordstore
    recipient_hash: {}
    safecontent: true
    usesymbols: false
