#!/bin/bash -eu
#
# "Prepares" for a proper SSH connection with a remote host:
# - copies the public key (id_rsa.pub) to authorized_keys
# - sends the terminfo of the local '$TERM' to the remote host
#

# $1 is user@host
(( $# == 1 ))

[[ $1 =~ ^([^[:blank:]]+)@([^[:blank:]]+)$ ]]

USER="${BASH_REMATCH[1]}"
HOST="${BASH_REMATCH[2]}"

KEY="$HOME/.ssh/id_rsa.pub"
[[ -f "$KEY" ]]

# check if the public key is in place
if ssh -o 'BatchMode=yes' "$USER@$HOST" 'true'; then
    echo "The public key is already in place" >&2
else
    echo "Copying the public key" >&2
    cat "$KEY" | ssh $USER@$HOST '
    [[ -d "$HOME/.ssh" ]] \
        || mkdir "$HOME/.ssh" \
        && cat > authorized_keys \
        && chmod 600 authorized_keys
    '
fi

echo "Copying the terminfo" >&2
infocmp "$TERM" | ssh $USER@$HOST '
    [[ -d "$HOME/.terminfo" ]] \
    || mkdir .terminfo \
    && cat >/tmp/ti \
    && tic /tmp/ti \
    && rm /tmp/ti
'

